terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0"
    }
  }
}

provider "azuread" {}

resource "azuread_user" "az104_user1" {
  user_principal_name = "az104-user1@ivanuksofia7gmail.onmicrosoft.com"
  display_name        = "az104-user1"
  password            = "AutoGeneratedSecurePassword123!"
  account_enabled     = true
  job_title           = "IT Lab Administrator"
  department          = "IT"
  usage_location      = "US"
}

resource "azuread_invitation" "external_user" {
  user_email_address = "sofiia.ivanytska.22@pnu.edu.ua"
  redirect_url       = "https://portal.azure.com"
}

resource "azuread_group" "it_lab_admins" {
  display_name     = "IT Lab Administrators"
  description      = "Administrators that manage the IT lab"
  security_enabled = true
  mail_enabled     = false
}

resource "azuread_group_member" "az104_user1_member" {
  group_object_id  = azuread_group.it_lab_admins.id
  member_object_id = azuread_user.az104_user1.id
}